### ISSUE TITLE
--noGui and --gameVersion crash on startup

### ISSUE THREAD

**Issue by nSadd** [Youded-byte/lunar-client-qt#10]
I can't find any launcher logs (if there are any) and the launcher doesnt print anything to the terminal
latest.log is empty as the game never even started

using both --noGui and --gameVersion together doesn't work (both work fine independently)

it opens java (titled "Genesis" instead of "Lunar Client" if that helps?) and then immediately exits

**Comment by Youded-byte** [comment]
Could you share the whole command you used to launch lunar-client-qt? It's possible that you are trying to load a version that you don't have installed, or using a different than supported version name. use the same versions as in lcqt, so for example for 1.8.9  just 1.8.

**Comment by nSadd** [comment]
ah i see, i was writting out the full version (1.8.9 instead of 1.8)
