### ISSUE TITLE
Lunar client still not starting after the fix

### ISSUE THREAD

**Issue by NLogDEV** [Youded-byte/lunar-client-qt#11]
Continuation of #7
Still, the Lunar client does not start with the error 'Failed to start process: No program defined'

**Comment by Youded-byte** [comment]
Launch the same version first from the official lunar client launcher. If it still doesn't work, then what operating system are you using? What is inside of your `%userprofile%\.lunarclient\offline\multiver` folder? And is there a java JRE?

**Comment by NLogDEV** [comment]
I've launched the same version first from the official lunar client launcher, it stills works
there's a jre in the .lunarcleint\jre folder (zulu17.34.19-ca-jre17.0.3-win_x64) but that's in the folder 4dcd188552ce8876d5e55e1f6d22505109bfa4cb

**Comment by NLogDEV** [comment]
Looks like the issue is fixed now.
