### ISSUE TITLE
lunar

### ISSUE THREAD

**Issue by dittye** [Youded-byte/lunar-client-qt#15]
it doesnt works last update it says 
OpenJDK 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
Exception in thread "main" java.lang.IllegalStateException: Failed to boot Minecraft
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)

Exception: java.lang.ClassCircularityError thrown from the UncaughtExceptionHandler in thread "main"

**Comment by Sweet-Tooth11** [comment]
Hello dittye,

To fix this error, please refer to this [Website](https://www.oracle.com/java/technologies/javase/largememory-pages.html).

**Comment by Youded-byte** [comment]
Share the version, and mod loader that you used as well.
