### ISSUE TITLE
illegal modification detected Please remove any Lunar Client modifications

### ISSUE THREAD

**Issue by shadowxrave** [Youded-byte/lunar-client-qt#26]
![Снимок экрана 2024-02-12 173833](https://github.com/Youded-byte/lunar-client-qt/assets/159794533/236ee76f-1c72-4e60-802a-6c61f9aadd5e)
![Снимок экрана 2024-02-12 173747](https://github.com/Youded-byte/lunar-client-qt/assets/159794533/ea4e8c84-5504-4986-8f2b-0e3f0ccb942c)

**Comment by mallusrgreatv2** [comment]
This is not LCQT2 support.

**Comment by shadowxrave** [comment]
I didnt understand anything, how do i solve this?

**Comment by Youded-byte** [comment]
Either download this project from [https://github.com/Youded-byte/lunar-client-qt/](https://github.com/Youded-byte/lunar-client-qt/releases) or then ask the developers of lcqt2 for help. They are two separate programs even though the name of the newer and now obsolete lcqt2 can be misleading.
