### ISSUE TITLE
It shows "Windows protected your PC" when I try to open qt.

### ISSUE THREAD

**Issue by darshadev2011** [Youded-byte/lunar-client-qt#27]
I downloaded the "windows.zip" file, extracted it and clicked on the "lunar-client-qt.exe" file and it showed the "Windows Protected your PC" error. I tried to launch it as an administrator but still doesn't work.

**Comment by Youded-byte** [comment]
This is normal on newer Windows version as I haven't payed Microsoft to be able to sign the program to verify it comes from here. It should only happen the first time, and you should click on the little gray text which reads "More info" and then click on "Run anyway".
