### ISSUE TITLE
v1_12 is read as 1.1.2 in launcher (and doesnt launch the game)

### ISSUE THREAD

**Issue by nSadd** [Youded-byte/lunar-client-qt#8]
<img width="118" alt="image" src="https://github.com/Youded-byte/lunar-client-qt/assets/53909427/f4c99e97-716f-48a9-9403-3effdefec2b1">
<img width="271" alt="image" src="https://github.com/Youded-byte/lunar-client-qt/assets/53909427/83d02c93-97fa-4689-944c-8cad2234d26c">

**Comment by Youded-byte** [comment]
Fixed.
